//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ESantiagoMensajeriaEntities : DbContext
    {
        public ESantiagoMensajeriaEntities()
            : base("name=ESantiagoMensajeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
    
        public virtual int UsuarioAdd(string username, string email, byte[] password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsuarioAdd", usernameParameter, emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<UsuarioCheck_Result> UsuarioCheck(string username, byte[] password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioCheck_Result>("UsuarioCheck", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<ContactosGetByIdUsuarioRemitente_Result> ContactosGetByIdUsuarioRemitente(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ContactosGetByIdUsuarioRemitente_Result>("ContactosGetByIdUsuarioRemitente", idUsuarioParameter);
        }
    
        public virtual ObjectResult<MensajeGetMessages_Result> MensajeGetMessages(Nullable<int> idUsuarioRemitente, Nullable<int> idUsuarioDestinatario)
        {
            var idUsuarioRemitenteParameter = idUsuarioRemitente.HasValue ?
                new ObjectParameter("IdUsuarioRemitente", idUsuarioRemitente) :
                new ObjectParameter("IdUsuarioRemitente", typeof(int));
    
            var idUsuarioDestinatarioParameter = idUsuarioDestinatario.HasValue ?
                new ObjectParameter("IdUsuarioDestinatario", idUsuarioDestinatario) :
                new ObjectParameter("IdUsuarioDestinatario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MensajeGetMessages_Result>("MensajeGetMessages", idUsuarioRemitenteParameter, idUsuarioDestinatarioParameter);
        }
    
        public virtual int MensajeSendMessage(Nullable<int> idUsuarioRemitente, Nullable<int> idUsuarioDestinatario, string mensaje)
        {
            var idUsuarioRemitenteParameter = idUsuarioRemitente.HasValue ?
                new ObjectParameter("IdUsuarioRemitente", idUsuarioRemitente) :
                new ObjectParameter("IdUsuarioRemitente", typeof(int));
    
            var idUsuarioDestinatarioParameter = idUsuarioDestinatario.HasValue ?
                new ObjectParameter("IdUsuarioDestinatario", idUsuarioDestinatario) :
                new ObjectParameter("IdUsuarioDestinatario", typeof(int));
    
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("Mensaje", mensaje) :
                new ObjectParameter("Mensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MensajeSendMessage", idUsuarioRemitenteParameter, idUsuarioDestinatarioParameter, mensajeParameter);
        }
    
        public virtual int ContactosAdd(Nullable<int> idUsuarioRemitente, Nullable<int> idUsuarioDestinatario)
        {
            var idUsuarioRemitenteParameter = idUsuarioRemitente.HasValue ?
                new ObjectParameter("IdUsuarioRemitente", idUsuarioRemitente) :
                new ObjectParameter("IdUsuarioRemitente", typeof(int));
    
            var idUsuarioDestinatarioParameter = idUsuarioDestinatario.HasValue ?
                new ObjectParameter("IdUsuarioDestinatario", idUsuarioDestinatario) :
                new ObjectParameter("IdUsuarioDestinatario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ContactosAdd", idUsuarioRemitenteParameter, idUsuarioDestinatarioParameter);
        }
    
        public virtual int ContactosDelete(Nullable<int> idUsuarioRemitente, Nullable<int> idUsuarioDestinatario)
        {
            var idUsuarioRemitenteParameter = idUsuarioRemitente.HasValue ?
                new ObjectParameter("IdUsuarioRemitente", idUsuarioRemitente) :
                new ObjectParameter("IdUsuarioRemitente", typeof(int));
    
            var idUsuarioDestinatarioParameter = idUsuarioDestinatario.HasValue ?
                new ObjectParameter("IdUsuarioDestinatario", idUsuarioDestinatario) :
                new ObjectParameter("IdUsuarioDestinatario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ContactosDelete", idUsuarioRemitenteParameter, idUsuarioDestinatarioParameter);
        }
    
        public virtual ObjectResult<UsuarioGetByUsername_Result> UsuarioGetByUsername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioGetByUsername_Result>("UsuarioGetByUsername", usernameParameter);
        }
    }
}
